maxPlatoonSize:         10
algorithmType:          0
statusMessageInterval:  
infoMessageInterval:    
timeHeadway:            2.5
standStillHeadway:      12.0
maxAllowedJoinTimeGap:  15.0
maxAllowedJoinGap:      90.0
desiredJoinTimeGap:     4.0
desiredJoinGap:         30.0
waitingStateTimeout:    25.0
cmdSpeedMaxAdjustment:  10.0
minAllowableHeadaway:   1.6
maxAllowableHeadaway:   4.0
headawayStableLowerBond: 1.7
headawayStableUpperBond: 3.9
minGap:                 22.0
maxGap:                 32.0
maxCrosstrackError:     0.8

# time allowed between consecutive incoming mobility operation STATUS messages
# from a follower member before it is considered non-communicative and dropped
# from the platoon (with all members behind it), ms
memberDropoutTimeout: 1001

# if true will force two vehicles to perform a front join rather than rear join
# (for testing purposes only)
test_front_join: false
