# Double: The minimum duration of a trajectory length
# Units: seconds
minimal_trajectory_duration : 6.0

# Double: The rate at which the Guidance Node will process message
# Units: Hz
spin_rate_hz: 10

# Double: Size of timesteps between stopped trajectory points when stopped
# Units: seconds
stop_timestep : 0.1

# Double: Downtrack distance between trajectory points
# Units: seconds
trajectory_step_size : 1.0

# Double: Downtrack distance between trajectory points
# Units: seconds
accel_limit_multiplier : 0.7
