#-----Heading PID constants
# deadband where control error is ignored, rad
pid_h_deadband: 0.0

# breakpoint where p value changes from kp1 to kp2, rad
pid_h_slope_break: 1.6 #large enough that kp2 will never be needed

# first proportional gain, rad/rad
pid_h_kp1: -0.8

# second proportional gain, rad/rad
pid_h_kp2: -1.0

# integral gain, rad/rad
pid_h_ki: 0.0 #initial guess NOT TUNED!

# derivative gain, rad/rad
pid_h_kd: 0.0 #initial guess NOT TUNED!

# min value allowed for integral term
pid_h_integral_min: -0.1 #initial guess NOT TUNED!

# max value allowed for integral term
pid_h_integral_max: 0.1 #initial guess NOT TUNED!


#-----CTE PID constants
# deadband where control error is ignored, m
pid_c_deadband: 0.0 #initial guess NOT TUNED!

# breakpoint where p value changes from kp1 to kp2, m
pid_c_slope_break: 5.0 #initial guess NOT TUNED!

# first proportional gain, rad/m
pid_c_kp1: 0.03

# second proportional gain, rad/m
pid_c_kp2: 0.06

# integral gain, rad/m
pid_c_ki: 0.01

# derivative gain, rad/m
pid_c_kd: 0.02

# min value allowed for integral term
pid_c_integral_min: -1.0 #initial guess NOT TUNED!

# max value allowed for integral term
pid_c_integral_max: 1.0 #initial guess NOT TUNED!


#-----Common PID constants
# expected time elapsed between calls to PID controllers, s
# This value needs to be 1/control_timer frequency that is set at bottom of initialize()
time_step: 0.03333

# Fraction of weight applied to heading PID instead of CTE PID.
# Value must be in [0, 1], where 0 only uses CTE and 1 only uses heading
gamma_h: 0.2

# max absolute value of steering angle output, rad
# TODO this needs to come from global vehicle config
max_steering_angle: 1.05 #approx 60 deg


#-----Non-PID values

# Max allowed longitudinal acceleration, m/s^2
# TODO better to get this from global vehicle config
max_accel: 1.5

# Max allowed speed to adjust the gap (this needs to be >= config speed limit), m/s
# TODO better to make this a delta above the vehicle's config max speed
speed_adjustment_cap: 12.0
