timeHeadway: 3.5
standStillHeadway: 22.0
maxAccel: 1.5
Kp: 0.55
Kd: 0.0 #0.1
Ki: 0.2 #0.035
maxValue: 2.0
minValue: -10.0
cmdTmestamp: 100
adjustmentCap: 15.0
dt: 0.1
integratorMax: 100
integratorMin: -100
wheelBase: 3.09
lowpassGain: 1.0
lookaheadRatio: 2.0 #1.7
minLookaheadDist: 15.0
correctionAngle: 0.0
