timeHeadway: 2.0
standStillHeadway: 22.0
maxAccel: 1.5
Kp: 0.3
Kd: 0.1
Ki: 0.035
max_value: 5.0
min_value: -1.0
CMD_TIMESTEP: 100
adjustmentCap: 3.5
dt: 0.1
integratorMax: 100
integratorMin: -100
wheelbase: 2.7
lowpass_gain: 0.05
lookahead_ratio: 2.5
min_lookahead_dist: 10.0
