timeHeadway: 2.0
standStillHeadway: 12.0
maxAccel: 1.0
Kp: 0.3
Kd: 0.1
Ki: 0.035
max_value: 11.0
min_value: -1.0
CMD_TIMESTEP: 100
adjustmentCap: 4.0
dt: 0.1
integratorMax: 100
integratorMin: -100
wheelbase: 0.5
lowpass_gain: 0.3
lookahead_ratio: 2.0
